### ISSUE TITLE
使用AndroidSwipeLayout时有问题

### ISSUE THREAD

**Issue by luckyjmcc** [Syehunter/RecyclerViewManager#2]
当使用AndroidSwipeLayout进行滑动删除的时候，正常。向下滑动recycleview时正常，但是向上滑动的时候，recycleview回不去就直接进行下刷新了。请问这个怎么处理？

when useing AndroidSwipeLayout  make item swipe to delete ,it works well. And it worked when srolling  recycleview down but  up not , the pull down to refresh view comes out before recycleview scroll to pre item。What causes this problem  ?

**Comment by Syehunter** [comment]
好的，谢谢反馈，这两天有时间的时候测试一下~

**Comment by Syehunter** [comment]
刚刚写了个测试的demo，使用AndroidSwipeLayout的时候没有出现您说的问题，有可能是其他的未知bug引起的，不知是否可以留个邮箱，看看问题具体出现在哪里？或者加我的QQ号，359128803

**Comment by Syehunter** [comment]
Um...Maybe I've found the problem that not caused by AndriodSwipeLayout. Just import the new version and try to rebuild your project again.

**Comment by luckyjmcc** [comment]
A responsible writer
